### ISSUE TITLE
Getting error when building

### ISSUE THREAD

**Issue by ali-habibzadeh** [kimamula/typedoc-markdown-theme#7]
`/node_modules/typescript/lib
/Users/alihabibzadeh/dc-web-api/node_modules/typedoc/dist/lib/output/renderer.js:100
                    throw new Error("Exception while loading \"" + filename + "\". You must export a `new Theme(renderer, basePath)` compatible
 class.\n" +
                    ^`

**Comment by jimfang** [comment]
Using TypeScript 2.7.2 from G:\build\dev\trunk\test\atf\atfbindings\atfnjs\node_modules\typedoc\node_modules\typescript\lib
G:\build\dev\trunk\test\atf\atfbindings\atfnjs\node_modules\typedoc\dist\lib\output\renderer.js:100
                    throw new Error("Exception while loading \"" + filename + "\". You must export a `new Theme(renderer, basePath)` compatible class.\n" +
                    ^

Error: Exception while loading "G:\build\dev\trunk\test\atf\atfbindings\atfnjs\node_modules\typedoc-markdown-theme\bin\theme.js". You must export a `new Theme(renderer, basePath)` compatible class.
TypeError: renderer.removePlugin is not a function
    at Renderer.prepareTheme (G:\build\dev\trunk\test\atf\atfbindings\atfnjs\node_modules\typedoc\dist\lib\output\renderer.js:100:27)
    at Renderer.render (G:\build\dev\trunk\test\atf\atfbindings\atfnjs\node_modules\typedoc\dist\lib\output\renderer.js:38:19)
    at CliApplication.Application.generateDocs (G:\build\dev\trunk\test\atf\atfbindings\atfnjs\node_modules\typedoc\dist\lib\application.js:102:23)
    at CliApplication.bootstrap (G:\build\dev\trunk\test\atf\atfbindings\atfnjs\node_modules\typedoc\dist\lib\cli.js:62:26)
    at CliApplication.Application [as constructor] (G:\build\dev\trunk\test\atf\atfbindings\atfnjs\node_modules\typedoc\dist\lib\application.js:41:15)
    at new CliApplication (G:\build\dev\trunk\test\atf\atfbindings\atfnjs\node_modules\typedoc\dist\lib\cli.js:35:42)
    at Object.<anonymous> (G:\build\dev\trunk\test\atf\atfbindings\atfnjs\node_modules\typedoc\bin\typedoc:4:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! atfnjs@0.0.1 doc: `typedoc --out doc --theme node_modules/typedoc-markdown-theme/bin --tsconfig tsconfig.json --readme README.md --target ES5`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atfnjs@0.0.1 doc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jimf\AppData\Roaming\npm-cache\_logs\2018-07-24T01_15_44_327Z-debug.log
